### ISSUE TITLE
Create "CutiesInMiami" (Twitterbot of pets, forked from CutePetsDenver)

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/tasks#22]
The instructions on how to do this is here: https://github.com/codeforamerica/CutePets

Note that there is an Miami-appropriate shelter we will need to find the ID for. We can probably find this on our own if we can't find the original person from the South Florida No-Kill Shelter who visited a Code for Miami meeting a couple of months ago.

**Comment by CristinaSolana** [comment]
Done.
