### ISSUE TITLE
Convince City of Hialeah to install a cellular GPS tracking device in the buses

### ISSUE THREAD

**Issue by danorys** [Code-for-Miami/tasks#46]
Dan Duffy has reached out to Jorge de la Nuez (305-681-5757 or jdelanuez@hialeahfl.gov) at the Transit Authority of the City of Hialeah about installing cellular GPS tracking devices on their buses to support the Transit Application.

**Comment by qtrandev** [comment]
Someone please add the contact information for any Hialeah official.

**Comment by danorys** [comment]
Dan Duffy met with Jorge de la Nuez, Transit Manager for Fleet Maintenance of the City of Hialeah, yesterday, who was interested in participating in an integrated transit solution to help passengers negotiate the various transit systems in Miami-Dade County. After showing Mr. de la Nuez the tracking device, he said their buses already have cellular GPS devices, and will speak with the City's supplier about making the real time location data available to Quyen Tran.

Fleet Maintenance is located in Building #3 at 900 East 56 Street, Hialeah, FL 33010. If you go, the only indication of this very large facility from the street is a mailbox with a barely-legible number 900 on the left side of 56th Street after you have passed the Police Station lot; if you reach the bend in the road, you have gone too far. 

Mr. de la Nuez can be reached at his office at (305) 681-5757 or his mobile at (305) 632-8316. If neither of those work, I was able to reach his secretary at (305) 769-7727. His e-mail address is jdelanuez@hialeahfl.org. 

Since the City of Hialeah buses are already equipped with cellular GPS tracking devices and Mr. de la Nuez is interested in sharing the data, I am closing this particular issue. Anyone interested in having me participating in further dialogue with the City of Hialeah on this topic can call or text me at 561-391-5703 or see me at one of the Code for Miami Meet Ups.
